### ISSUE TITLE
Realtime getting new messages

### ISSUE THREAD

**Issue by Nihuaway00** [Nihuaway/Bazalt#3]
### Firstly, getting chatKey:
- when user request chat, it return chat data with key
- key will be save to state manager with chatID

### Secondly:
- send encrypted data to server
- server proccess their
- return encrypted message data
- decrypt on client with chatkey
- save to state manager

### Tasks:
- [x] get and save chat key
- [x] send message to server
- [x]  get data and decrypt with chatKey
- [x] update messages
- [x] work with files
